common:
  msg_source: 1                                         
  send_packet_ros: false
  send_point_cloud_ros: true
  send_packet_proto: false
  send_point_cloud_proto: false
  pcap_path: /home/robosense/lidar.pcap

lidar:
  - driver:
      lidar_type: RSHELIOS                      
      frame_id: rslidar
      msop_port: 6699
      difop_port: 7788
      start_angle: 0
      end_angle: 360
      min_distance: 0.2
      max_distance: 200
      use_lidar_clock: false
      pcap_rate: 1
      pcap_repeat: true
    ros:
      ros_send_point_cloud_topic: /points_raw
      ros_send_packet_topic: /rslidar_packets
      ros_frame_id: rslidar
      ros_point_cloud_2d: false
      ros_point_type: XYZI
      ros_send_scan_topic: /scan
